# Automatically generated by msquared.MGen on 2018-05-26 16:23:38.437909.
# DO NOT MODIFY.

.PHONY: clean test install uninstall

/home/pranav/C++/Stealth/Tensor3/build/test.o: /home/pranav/C++/Stealth/Tensor3/test/test.cpp 
	g++ -fPIC -c -O3 -flto -march=native -std=c++17 /home/pranav/C++/Stealth/Tensor3/test/test.cpp -o /home/pranav/C++/Stealth/Tensor3/build/test.o

/home/pranav/C++/Stealth/Tensor3/test/test: /home/pranav/C++/Stealth/Tensor3/build/test.o 
	g++ -O3 -flto -march=native /home/pranav/C++/Stealth/Tensor3/build/test.o  -o /home/pranav/C++/Stealth/Tensor3/test/test 

test: /home/pranav/C++/Stealth/Tensor3/test/test
	test/test

install: 
	sudo mkdir -p /usr/local/include/Stealth
	printf '#include "/home/pranav/C++/Stealth/Tensor3/include/Functors/BinaryFunctors.hpp"\n#include "/home/pranav/C++/Stealth/Tensor3/include/Functors/UnaryFunctors.hpp"\n#include "/home/pranav/C++/Stealth/Tensor3/include/Operations/MatrixOps.hpp"\n#include "/home/pranav/C++/Stealth/Tensor3/include/Operations/NullaryOperations.hpp"\n#include "/home/pranav/C++/Stealth/Tensor3/include/Expressions/ElemWiseBinaryExpr.hpp"\n#include "/home/pranav/C++/Stealth/Tensor3/include/Operations/BlockOperations.hpp"\n#include "/home/pranav/C++/Stealth/Tensor3/include/Operations/ElemWiseUnaryOps.hpp"\n#include "/home/pranav/C++/Stealth/Tensor3/include/core/Tensor3Base.hpp"\n#include "/home/pranav/C++/Stealth/Tensor3/include/core/DenseStorage.hpp"\n#include "/home/pranav/C++/Stealth/Tensor3/include/Expressions/ElemWiseUnaryExpr.hpp"\n#include "/home/pranav/C++/Stealth/Tensor3/include/Operations/ElemWiseBinaryOps.hpp"\n#include "/home/pranav/C++/Stealth/Tensor3/include/Functors/NullaryFunctors.hpp"\n#include "/home/pranav/C++/Stealth/Tensor3/include/core/Tensor3.hpp"\n#include "/home/pranav/C++/Stealth/Tensor3/include/Expressions/ElemWiseNullaryExpr.hpp"\n#include "/home/pranav/C++/Stealth/Tensor3/include/core/ForwardDeclarations.hpp"\n#include "/home/pranav/C++/Stealth/Tensor3/include/Expressions/BlockExpr.hpp"\n' > build/install_Tensor3
	sudo mv build/install_Tensor3 /usr/local/include/Stealth/Tensor3

uninstall: 
	sudo rm -rf /usr/local/include/Stealth/Tensor3
	sudo rmdir /usr/local/include/Stealth

